pub const USHRT_MAX: i32 = 65535;

pub const CMD_DB_RRQ: i8 = 7; // Read in some kind of data from the machine
pub const CMD_USER_WRQ: i8 = 8; // Upload the user information from PC to terminal.
pub const CMD_USERTEMP_RRQ: u16 = 9; // Read some fingerprint template or some kind of data entirely
pub const CMD_USERTEMP_WRQ: i8 = 10; // Upload some fingerprint template
pub const CMD_OPTIONS_RRQ: i8 = 11; // Read in the machine some configuration parameter
pub const CMD_OPTIONS_WRQ: i8 = 12; // Set machines configuration parameter
pub const CMD_ATTLOG_RRQ: u16 = 13; // Read all attendance record
pub const CMD_CLEAR_DATA: i8 = 14; // clear Data
pub const CMD_CLEAR_ATTLOG: i8 = 15; // Clear attendance records
pub const CMD_DELETE_USER: i8 = 18; // Delete some user
pub const CMD_DELETE_USERTEMP: i8 = 19; // Delete some fingerprint template
pub const CMD_CLEAR_ADMIN: i8 = 20; // Cancel the manager
pub const CMD_USERGRP_RRQ: i8 = 21; // Read the user grouping
pub const CMD_USERGRP_WRQ: i8 = 22; // Set users grouping
pub const CMD_USERTZ_RRQ: i8 = 23; // Read the user Time Zone set
pub const CMD_USERTZ_WRQ: i8 = 24; // Write the user Time Zone set
pub const CMD_GRPTZ_RRQ: i8 = 25; // Read the group Time Zone set
pub const CMD_GRPTZ_WRQ: i8 = 26; // Write the group Time Zone set
pub const CMD_TZ_RRQ: i8 = 27; // Read Time Zone set
pub const CMD_TZ_WRQ: i8 = 28; // Write the Time Zone
pub const CMD_ULG_RRQ: i8 = 29; // Read unlocks combination
pub const CMD_ULG_WRQ: i8 = 30; // write unlocks combination
pub const CMD_UNLOCK: i8 = 31; // unlock
pub const CMD_CLEAR_ACC: i8 = 32; // Restores Access Control set to the default condition.
pub const CMD_CLEAR_OPLOG: i8 = 33; // Delete attendance machines all attendance record.
pub const CMD_OPLOG_RRQ: i8 = 34; // Read manages the record
pub const CMD_GET_FREE_SIZES: u16 = 50; // Obtain machines condition, like user recording number and so on
pub const CMD_ENABLE_CLOCK: i8 = 57; // Ensure the machine to be at the normal work condition
pub const CMD_STARTVERIFY: i8 = 60; // Ensure the machine to be at the authentication condition
pub const CMD_STARTENROLL: i8 = 61; // Start to enroll some user, ensure the machine to be at the registration user condition
pub const CMD_CANCELCAPTURE: i8 = 62; // Make the machine to be at the waiting order status, please refers to the CMD_STARTENROLL description.
pub const CMD_STATE_RRQ: i8 = 64; // Gain the machine the condition
pub const CMD_WRITE_LCD: i8 = 66; // Write LCD
pub const CMD_CLEAR_LCD: i8 = 67; // Clear the LCD captions clear screen.
pub const CMD_GET_PINWIDTH: i8 = 69; // Obtain the length of user’s serial number
pub const CMD_SMS_WRQ: i8 = 70; // Upload the short message.
pub const CMD_SMS_RRQ: i8 = 71; // Download the short message
pub const CMD_DELETE_SMS: i8 = 72; // Delete the short message
pub const CMD_UDATA_WRQ: i8 = 73; // Set user’s short message
pub const CMD_DELETE_UDATA: i8 = 74; // Delete user’s short message
pub const CMD_DOORSTATE_RRQ: i8 = 75; // Obtain the door condition
pub const CMD_WRITE_MIFARE: i8 = 76; // Write the Mifare card
pub const CMD_EMPTY_MIFARE: i8 = 78; // Clear the Mifare card
pub const _CMD_GET_USERTEMP: i8 = 88; // UNDOCUMENTED! get an specific user template uid, fid
pub const _CMD_SAVE_USERTEMPS: i8 = 110; // UNDOCUMENTED! save user and multiple templates!
pub const _CMD_DEL_USER_TEMP: i16 = 134; // UNDOCUMENTED! delete an specific user template uid, fid16
pub const CMD_GET_TIME: i16 = 201; // Obtain the machine time
pub const CMD_SET_TIME: i16 = 202; // Set machines time
pub const CMD_REG_EVENT: i16 = 500; // Register the event

pub const CMD_CONNECT: i16 = 1000; // Connections requests
pub const CMD_EXIT: i16 = 1001; // Disconnection requests
pub const CMD_ENABLEDEVICE: i16 = 1002; // Ensure the machine to be at the normal work condition
pub const CMD_DISABLEDEVICE: i16 = 1003; // Make the machine to be at the shut-down condition, generally demonstrates ‘in the work ...’on LCD
pub const CMD_RESTART: i16 = 1004; // Restart the machine.
pub const CMD_POWEROFF: i16 = 1005; // Shut-down power source
pub const CMD_SLEEP: i16 = 1006; // Ensure the machine to be at the idle state.
pub const CMD_RESUME: i16 = 1007; // Awakens the sleep machine temporarily not to support
pub const CMD_CAPTUREFINGER: i16 = 1009; // Captures fingerprints picture
pub const CMD_TEST_TEMP: i16 = 1011; // Test some fingerprint exists or does not
pub const CMD_CAPTUREIMAGE: i16 = 1012; // Capture the entire image
pub const CMD_REFRESHDATA: i16 = 1013; // Refresh the machine interior data
pub const CMD_REFRESHOPTION: i16 = 1014; // Refresh the configuration parameter
pub const CMD_TESTVOICE: i16 = 1017; // Play voice
pub const CMD_GET_VERSION: i16 = 1100; // Obtain the firmware edition
pub const CMD_CHANGE_SPEED: i16 = 1101; // Change transmission speed
pub const CMD_AUTH: i16 = 1102; // Connections authorizations
pub const CMD_PREPARE_DATA: u16 = 1500; // Prepares to transmit the data
pub const CMD_DATA: u16 = 1501; // Transmit a data packet
pub const CMD_FREE_DATA: u16 = 1502; // Clear machines opened buffer
pub const CMD_PREPARE_BUFFER: u16 = 1503; // UNDOCUMENTED initialize buffer for partial reads!
pub const CMD_READ_BUFFER: u16 = 1504; // UNDOCUMENTED ready a partial chunk of data from buffer

pub const CMD_ACK_OK: u16 = 2000; // Return value for order perform successfully
pub const CMD_ACK_ERROR: i16 = 2001; // Return value for order perform failed
pub const CMD_ACK_DATA: i16 = 2002; // Return data
pub const CMD_ACK_RETRY: i16 = 2003; // * Regstered event occorred */
pub const CMD_ACK_REPEAT: i16 = 2004; // Not available
pub const CMD_ACK_UNAUTH: i16 = 2005; // Connection unauthorized

pub const CMD_ACK_UNKNOWN: u16 = 0xffff; // Unkown order
pub const CMD_ACK_ERROR_CMD: u16 = 0xfffd; // Order false
pub const CMD_ACK_ERROR_INIT: u16 = 0xfffc;
///* Not Initializated */
pub const CMD_ACK_ERROR_DATA: u16 = 0xfffb; // Not available

pub const EF_ATTLOG: i8 = 1; // Be real-time to verify successfully
pub const EF_FINGER: i8 = 1 << 1; // be real–time to press fingerprint be real time to return data type sign
pub const EF_ENROLLUSER: i8 = 1 << 2; // Be real-time to enroll user
pub const EF_ENROLLFINGER: i8 = 1 << 3; // be real-time to enroll fingerprint
pub const EF_BUTTON: i8 = 1 << 4; // be real-time to press button
pub const EF_UNLOCK: i8 = 1 << 5; // be real-time to unlock
pub const EF_VERIFY: i8 = 1 << 7; // be real-time to verify fingerprint
pub const EF_FPFTR: i16 = 1 << 8; // be real-time capture fingerprint minutia
pub const EF_ALARM: i16 = 1 << 9; // Alarm signal

pub const USER_DEFAULT: i8 = 0;
pub const USER_ENROLLER: i8 = 2;
pub const USER_MANAGER: i8 = 6;
pub const USER_ADMIN: i8 = 14;

pub const FCT_ATTLOG: i8 = 1;
pub const FCT_WORKCODE: i8 = 8;
pub const FCT_FINGERTMP: i8 = 2;
pub const FCT_OPLOG: i8 = 4;
pub const FCT_USER: u32 = 5;
pub const FCT_SMS: i8 = 6;
pub const FCT_UDATA: i8 = 7;

pub const MACHINE_PREPARE_DATA_1: i16 = 20560; // 0x5050
pub const MACHINE_PREPARE_DATA_2: i16 = 32130; // 0x7282
